#define AUTO_SHIFT_TIMEOUT 135
#define MOUSEKEY_INTERVAL 1
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_WHEEL_DELAY 0
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
#define USB_MAX_POWER_CONSUMPTION 50
